-- MySQL Script generated by MySQL Workbench
-- ter 29 jul 2025 15:00:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ecommerce` ;
USE `db_ecommerce` ;

-- -----------------------------------------------------
-- Table `db_ecommerce`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`persons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NULL DEFAULT NULL,
  `phone` BIGINT(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`addresses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `complement` VARCHAR(32) NULL DEFAULT NULL,
  `city` VARCHAR(32) NOT NULL,
  `state` VARCHAR(32) NOT NULL,
  `country` VARCHAR(32) NOT NULL,
  `zip_code` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_addresses_persons_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_addresses_persons`
    FOREIGN KEY (`person_id`)
    REFERENCES `db_ecommerce`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `person_id` INT(11) NOT NULL,
  `login` VARCHAR(64) NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `is_admin` TINYINT(4) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_users_persons_idx` (`person_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_persons`
    FOREIGN KEY (`person_id`)
    REFERENCES `db_ecommerce`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`carts` (
  `id` INT(11) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `address_id` INT(11) NULL DEFAULT NULL,
  `freight` DECIMAL(10,2) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_carts_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_carts_addresses_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_carts_addresses`
    FOREIGN KEY (`address_id`)
    REFERENCES `db_ecommerce`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`products` (
  `id` INT(11) NOT NULL,
  `product` VARCHAR(64) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `width` DECIMAL(10,2) NOT NULL,
  `height` DECIMAL(10,2) NOT NULL,
  `length` DECIMAL(10,2) NOT NULL,
  `weight` DECIMAL(10,2) NOT NULL,
  `url` VARCHAR(128) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`carts_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`carts_products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cart_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `removed_at` DATETIME NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_carts_products_carts_idx` (`cart_id` ASC) VISIBLE,
  INDEX `FK_carts_products_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_cartsproducts_carts`
    FOREIGN KEY (`cart_id`)
    REFERENCES `db_ecommerce`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartsproducts_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`orders_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`orders_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cart_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `order_status_id` INT(11) NOT NULL,
  `total_value` DECIMAL(10,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_orders_carts_idx` (`cart_id` ASC) VISIBLE,
  INDEX `FK_orders_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_orders_status_idx` (`order_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_carts`
    FOREIGN KEY (`cart_id`)
    REFERENCES `db_ecommerce`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_ordersstatus`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `db_ecommerce`.`orders_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`products_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`products_categories` (
  `id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `product_id`),
  INDEX `fk_products_categories_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_productscategories_categories`
    FOREIGN KEY (`id`)
    REFERENCES `db_ecommerce`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productscategories_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `db_ecommerce`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`users_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`users_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `log` VARCHAR(128) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(128) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `url` VARCHAR(128) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_logs_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_userslogs_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`users_passwords_recoveries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`users_passwords_recoveries` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `recovered_at` DATETIME NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_passwords_recoveries_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_userspasswordsrecoveries_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ecommerce`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_ecommerce`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ecommerce`.`sessions` (
  `id` VARCHAR(64) NOT NULL,
  `ip_address` VARCHAR(45) NOT NULL,
  `user_agent` VARCHAR(255) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sessions_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_sessions_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_ecommerce`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
