name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_ecommerce
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql
          coverage: none
      - name: Install deps
        run: composer install --no-interaction --prefer-dist
      - name: Prepare DB schema
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USERNAME: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE_NAME: db_ecommerce
        run: |
          php -r '$sql=file_get_contents("src/infra/database/create-tables.sql"); $pdo=new PDO("mysql:host=127.0.0.1;port=3306;dbname=mysql","root","root"); foreach(array_filter(array_map("trim", explode(";", $sql))) as $stmt){ if($stmt){ $pdo->exec($stmt); } }'
      - name: Set env for tests
        run: |
          echo "MYSQL_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "MYSQL_USERNAME=root" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=root" >> $GITHUB_ENV
          echo "MYSQL_DATABASE_NAME=db_ecommerce" >> $GITHUB_ENV
      - name: PHPStan
        run: ./vendor/bin/phpstan analyse src --no-progress
      - name: PHPUnit
        run: ./vendor/bin/phpunit -c phpunit.xml.dist
